./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 2 --low 4 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 3 --low 3 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 4 --low 2 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 5 --low 5 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 2 --low 8 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 4 --low 8 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 8 --low 4 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 100 --high 10 --low 10 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 0 --high 2 --low 8 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 0 --high 4 --low 8 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 0 --high 8 --low 4 --data new
./run_experiments.sh --repl $1 --config_name bo-selector --iid 0 --high 10 --low 10 --data new