./run_experiments.sh --repl $1 --config_name random-selector --iid 0 --high 2 --low 4 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 0 --high 2 --low 4 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 0 --high 3 --low 3 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 0 --high 3 --low 3 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 0 --high 4 --low 2 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 0 --high 4 --low 2 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 0 --high 5 --low 5 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 0 --high 5 --low 5 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 100 --high 2 --low 4 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 100 --high 2 --low 4 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 100 --high 3 --low 3 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 100 --high 3 --low 3 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 100 --high 4 --low 2 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 100 --high 4 --low 2 --data new
./run_experiments.sh --repl $1 --config_name random-selector --iid 100 --high 5 --low 5 --data new
./run_experiments.sh --repl $1 --config_name tree-selector --iid 100 --high 5 --low 5 --data new