./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-selector-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-hdh-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 15 --low 25 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 25 --low 15 --data same --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 30 --low 10 --data same --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name no-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name always-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name random-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name fixed-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name tree-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name bo-all-pca --iid 0 --high 30 --low 10 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 15 --low 25 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 25 --low 15 --data new --delay no
./run_experiments.sh --repl $1 --config_name online-all-pca --iid 0 --high 30 --low 10 --data new --delay no
